### ISSUE TITLE
may you clarify how it is better than networkx?

### ISSUE THREAD

**Issue by Sandy4321** [networkdynamics/zenlib#30]
may you clarify how it is better than networkx?

from this video, it is not clear
Using Python for large scale network analysis #MP35
https://www.youtube.com/watch?v=7pZH3BsiexM

do you have more videos?

**Comment by druths** [comment]
It's a *lot* faster than networkx, which is implemented entirely in 
python.  In fact, python code that uses zen is faster than python code 
that uses networkx.

------ Original Message ------

**Comment by Sandy4321** [comment]
but was is about memory use
can your code run data with much bigger size than networkx?

**Comment by druths** [comment]
Yes - much larger.

------ Original Message ------

**Comment by Sandy4321** [comment]
so maybe you will try it works on Windows
majority of people use Windows

**Comment by druths** [comment]
True - supporting Windows properly would be wonderful.  The reality is 
that most network analysts and scientists I'm familiar with work on unix 
- and that's really all the bandwidth we have to support.

------ Original Message ------

**Comment by Sandy4321** [comment]
may you recommend good pure C++ implementation?
